import Head from "next/head";
import Map from "../components/map";

const about = () => {
  return (
    <div className="bg-black font-serif text-sm md:text-base text-white pt-20">
      <Head>
        <title>guide</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="md:mx-48 mt-30 h-screen">
        <div className="h-auto">
          <h1 className="text-center text-2xl mb-10">開催概要</h1>
        </div>
        <div className="md:flex md:flex-row md:flex-wrap justify-center">
          <div className="mdw-1/2 px-5">
            <div className="p-5 border-y border-gray-500 flex flex-row flex-wrap justify-self-start">
              <h1 className="w-1/3">・開催期間</h1>
              <h1 className="">2023年3月8日（水）〜3月9日（木）</h1>
            </div>

            <div className="p-5 border-y border-gray-500 flex flex-row flex-wrap justify-self-start">
              <h1 className=" w-1/3">・会 場</h1>
              <h1 className="">パルコール嬬恋スキーリゾート</h1>
            </div>
            <div className="p-5 border-y border-gray-500 flex flex-row flex-wrap justify-self-start">
              <h1 className=" w-1/3">・料 金</h1>
              <h1 className="">
                15,000円
                <br />
                ホテル料金、リフト券、夕食、朝食、イベント参加券がセットになった料金です。
              </h1>
            </div>
            <div className="p-5 border-y border-gray-500 flex flex-row flex-wrap justify-self-start">
              <h1 className=" w-1/3">・お問い合わせ</h1>
              <h1 className="">drop.snowboarding@gmail.com</h1>
            </div>
            <div className="p-5 border-y border-gray-500 flex flex-row flex-wrap justify-self-start">
              <h1 className=" w-1/3">・内容</h1>
              <h1 className="">
                スノーボードに関するイベント・アフターパーティー
              </h1>
            </div>
            <div className="p-5 border-y border-gray-500 flex flex-row flex-wrap justify-self-start">
              <h1 className=" w-1/3">・主催</h1>
              <h1 className=""> shuffle snowboarding・ssba 運営</h1>
            </div>
            <div className="p-5 border-y border-gray-500 ">
              <h1 className=" text-gray-400 text-sm">
                ※イベント料金に交通費は含まれておりません。
                <br />
                　アクティビティはイベント料金をお支払いされた方のみ無料で参加できます。
              </h1>
            </div>
          </div>
          <div className="w-1/2 px-5">{/* <Map /> */}</div>
        </div>
      </div>
    </div>
  );
};

export default about;
