import Head from "next/head";

const guide = () => {
  return (
    <div className="bg-black font-serif text-white md:pb-40 py-10 md:px-40 px-4 leading-loose">
      <Head>
        <title>guide</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-auto ">
        <div className="md:mx-40 mb-10 md:pt-10">
          <h1 className="text-3xl text-center border-b mb-10 md:mt-20">
            開催期間
          </h1>
          <p className="text-center">2023年3月8日（水）～2023年3月9日（木）</p>
        </div>
        <div className="md:mx-40 mb-10 mt-20">
          <h1 className="text-3xl text-center border-b mb-10 mt-20">料金</h1>
          <p className="text-center">
            15000円
            <br />
            ホテル料金、リフト券、夕食、朝食、イベント参加券がセットになった料金です。
          </p>
        </div>
        <div className="md:mx-40 mb-10 mt-20">
          <h1 className="text-3xl text-center border-b mb-10 mt-20">
            予約について
          </h1>
          <p className="text-center">
            予約開始は１月上旬
            <br />
            予約はオンラインのみ、本サイトにて予約開始
            <br />
            30日前以降は100%のキャンセル料が発生しますのでご注意下さい。
            <br />
          </p>
        </div>

        <div className="md:mx-40 mb-10 mt-20">
          <h1 className="text-3xl text-center border-b mb-10 mt-20">
            天候について
          </h1>
          <p className="text-center">
            雨天でも開催しますが、警報発令時などスタッフが危険と判断した場合は中止します。
          </p>
        </div>

        <div className="md:mx-40 mb-10 mt-20">
          <h1 className="text-3xl text-center border-b mb-10 mt-20">
            決済手段
          </h1>
          <p className="text-center">
            VISA / mastercard / maestro / AMERICAN EXPRESS / /Apple Pay / Google
            Pay
          </p>
        </div>

        <div className="md:mx-40 mb-10 mt-20">
          <h1 className="text-3xl text-center border-b mb-10 mt-20">
            交通手段
          </h1>
          <p className="text-center">自家用車でのお越しになります。</p>
        </div>

        <div className="md:mx-40 mb-10 mt-20">
          <h1 className="text-3xl text-center border-b mb-10 mt-20">
            当日について
          </h1>
          <p className="text-center">
            当日　8時20分　受付開始
            <br />
            2日目　16時00分　解散
            <br />
            予定
          </p>
        </div>
      </div>
    </div>
  );
};

export default guide;
