import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Map from "../components/map";

export default function Home() {
  return (
    <div className="bg-black font-serif text-sm md:text-base tracking-wide leading-loose pb-20">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-white">
        <div className="main">
          <div className="relative w-screen h-auto">
            <Image
              src="/image02.png"
              width={1920}
              height={1080}
              priority
              alt="drop bgimage"
            />
          </div>
        </div>
        <div className="xl:mx-10 mt-40 h-auto xl:flex xl:flex-row xl:flex-wrap xl:justify-center">
          <div className="xl:mx-10 xl:w-1/4">
            <h1 className="text-center m-4 text-xl">
              スノーボードをLifeStyleへ。
            </h1>
            <h2 className="text-center xl:text-left">
              年々人口が減少するスノーシーンにおいて、
              <br />
              次世代を担う学生がリアルなスノーボードに触れ、
              <br />
              ウィンタースポーツをLifeStyleの１つとする
              <br />
              きっかけとなるべく今回のイベントを開催。
              <br />
              ウィンタースポーツに興味を持ち、
              <br />
              貴重な時間を使ってウィンタースポーツを
              <br />
              楽しんでいる学生に、この一時だけでなく
              <br />
              生涯を通してウィンタースポーツを楽しんでもらいたい。
            </h2>
          </div>
          <div className="xl:mx-10 m-5 xl:w-1/4 xl:flex xl:flex-col xl:flex-wrap xl:justify-center grid justify-items-center">
            <Image src="/image03.jpg" width={500} height={500} alt="image03" />
          </div>
        </div>
        <div className="xl:mx-10 mt-40 xl:h-auto xl:flex xl:flex-row xl:flex-wrap xl:justify-center grid justify-items-center">
          <div className="xl:mx-10 xl:w-1/4 text-center">
            <h1 className=" text-5xl">DROP</h1>
            <h2 className="text-2xl">22-23</h2>
            <h3 className="text-xl my-5">"スノーボードをLifeStyleへ"</h3>
            <h2 className="text-4xl">3/8 - 3/9</h2>
            <h2 className="text-3xl my-5">パルコール嬬恋</h2>
            <h2 className="text-3xl my-5">15,000JPY</h2>
          </div>
          <div className="m-20 xl:mx-10 xl:w-1/4 xl:flex xl:flex-col xl:flex-wrap xl:justify-center">
            <Image src="/logo02.png" width={500} height={500} alt="image03" />
          </div>
        </div>
        <div className="xl:mx-48 xl:mt-40">
          <div className="h-auto flex flex-col flex-wrap justify-center">
            <h1 className="text-center text-2xl ">新着情報</h1>
            <div className="my-10 py-10 mx-5 border-y border-gray-500 flex flex-row flex-wrap justify-center">
              <h1 className="text-center text-gray-200 mx-10">12/24 </h1>
              <h1 className="text-center mx-10 ">サイトを公開しました。</h1>
            </div>
          </div>
        </div>
        <div className="xl:mx-48 xl:mt-40 mt-20">
          <div className="h-auto justify-center">
            <h1 className="text-center text-2xl ">タイムスケジュール</h1>
            <div className="my-10 py-10">
              <h1 className="text-center ">coming soon......</h1>
            </div>
          </div>
        </div>
        <div className="xl:mx-48 xl:my-40 my-20">
          <div className="h-auto">
            <h1 className="text-center text-2xl mb-10">開催概要</h1>
          </div>
          <div className="xl:flex xl:flex-row xl:flex-wrap xl:justify-center">
            <div className="xl:w-1/2 px-5">
              <div className="p-5 border-y border-gray-500 flex flex-row flex-wrap justify-self-start">
                <h1 className="w-1/3">・開催期間</h1>
                <h1 className="">2023年3月8日（水）〜3月9日（木）</h1>
              </div>
              <div className="p-5 border-y border-gray-500 flex flex-row flex-wrap justify-self-start">
                <h1 className=" w-1/3">・会 場</h1>
                <h1 className="">パルコール嬬恋スキーリゾート</h1>
              </div>
              <div className="p-5 border-y border-gray-500 flex flex-row flex-wrap justify-self-start">
                <h1 className=" w-1/3">・料 金</h1>
                <h1 className="">15,000円</h1>
              </div>
              <div className="p-5 border-y border-gray-500 flex flex-row flex-wrap justify-self-start">
                <h1 className=" w-1/3">・お問い合わせ</h1>
                <h1 className="">drop.snowboarding@gmail.com</h1>
              </div>
              <div className="p-5 border-y border-gray-500 ">
                <h1 className=" text-gray-400 text-sm">
                  ※イベント料金に交通費は含まれておりません。
                  <br />
                  　アクティビティはイベント料金をお支払いされた方のみ無料で参加できます。
                </h1>
              </div>
            </div>
            <div className="xl:w-1/2 w-screen h-72 px-5">
              <Map />
            </div>
          </div>
        </div>
        <div className="xl:mx-48 xl:mt-40">
          <div className="h-auto text-center justify-center">
            <h1 className="text-2xl ">協賛企業</h1>
            <div className="my-10 py-10 flex flex-row flex-wrap justify-center">
              <div className="m-10 border  border-gray-500">
                <Image
                  src="/yonex.png"
                  width={200}
                  height={200}
                  alt="yonex logo"
                />
                <Link href="https://www.yonex.co.jp/snowboards/">YONEX</Link>
              </div>
              <div className="m-10 border  border-gray-500">
                <div className="p-5">
                  <Image
                    src="/burton.png"
                    width={150}
                    height={150}
                    alt="burton logo"
                  />
                </div>
                <Link href="https://www.yonex.co.jp/snowboards/">BURTON</Link>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
