import Head from "next/head";
import Link from "next/link";

const thanks = () => {
  return (
    <div className="bg-black font-serif text-sm md:text-base text-white pt-20 h-screen w-screen flex justify-center items-center">
      <Head>
        <title>guide</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="md:mx-48 mt-30">
        <div className="text-center flex ">
          <h1 className=" text-xl mb-10">
            ご予約ありがとうございました。
            <br />
            <br />
            当会場まで気をつけてお越しくださいませ。
            <br />
            <br />
            <br />
            <Link className="text-sm " href="/">
              ホームへ戻る
            </Link>
          </h1>
        </div>
      </div>
    </div>
  );
};

export default thanks;
